set -g mouse on

set -g default-terminal "tmux-256color"

# make colors inside tmux look the same as outside of tmux
# see https://github.com/tmux/tmux/issues/696
# see https://stackoverflow.com/a/41786092
set-option -ga terminal-overrides ",tmux-256color:Tc"

# Alt-v to split vertically
bind-key -n M-v split-window -v

# Alt-h to split horizontally
bind-key -n M-h split-window -h

# alt+directions navigates through panes
bind-key -n M-left select-pane -L
bind-key -n M-right select-pane -R
bind-key -n M-up select-pane -U
bind-key -n M-down select-pane -D

# Alt-d to close a pane
bind-key -n M-d kill-pane

# New copy mode shortcut
bind-key -n C-Space copy-mode

# Session shortcuts
bind-key -n M-n new-window
bind-key -n M-w detach
bind-key -n M-t next-window
bind-key -n M-e previous-window
bind-key -n M-r command-prompt -I "#W" "rename-window '%%'"


# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'jimeh/tmux-themepack'

# Theme definition
set -g @themepack 'powerline/double/cyan'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
